# Generated by Django 6.0 on 2025-12-15 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Sensor value')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp of the reading')),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('high', 'High'), ('low', 'Low')], default='valid', max_length=20, verbose_name='Validation status')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='nodes.node', verbose_name='Node')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor', verbose_name='Sensor')),
            ],
            options={
                'verbose_name': 'Reading',
                'verbose_name_plural': 'Readings',
                'ordering': ['-timestamp'],
            },
        ),
    ]
