# Generated by Django 6.0 on 2025-12-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='reading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last update'),
        ),
    ]
