# Generated by Django 6.0 on 2025-12-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_reading_created_at_reading_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='updated_at',
        ),
    ]
