# Generated by Django 6.0 on 2025-12-15 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletion date')),
                ('name', models.CharField(max_length=100, verbose_name='Sensor name')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('pressure', 'Pressure'), ('luminosity', 'Luminosity'), ('wind', 'Wind')], max_length=20, verbose_name='Sensor type')),
                ('model', models.CharField(max_length=50, verbose_name='Sensor model')),
                ('unit', models.CharField(max_length=10, verbose_name='Unit of measure')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='nodes.node', verbose_name='Node')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'unique_together': {('node', 'name')},
            },
        ),
    ]
