# Generated by Django 6.0 on 2025-12-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high', 'High'), ('low', 'Low')], max_length=20, verbose_name='Alert type')),
                ('detected_value', models.FloatField(verbose_name='Detected value')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended')], default='pending', max_length=20, verbose_name='Alert status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
