# Generated by Django 6.0 on 2025-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('researcher', 'Investigador')], default='researcher', max_length=20, verbose_name='Rol del usuario'),
        ),
    ]
